In [5]:
# Question 1
# Ans) NumPy is a library for the Python programming language,
# adding support for large, multi-dimensional arrays and matrices, along with a large collection
# of high-level mathematical functions to operate on these arrays.

In [6]:
# Question 2
# NumPy arrays are much faster and have strict requirements on the homogeneity of the objects. For example,
# a NumPy array of strings can only contain strings and no other data types,
# but a Python list can contain a mixture of strings, numbers, booleans and other objects.

In [12]:
import numpy as np

In [13]:
#Question 3 
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [14]:
# shape of array
arr.shape

(3, 4)

In [15]:
# dimension of array
arr.ndim

2

In [17]:
# Question 4
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [18]:
# accessing the first row of the array
arr[0]

array([1, 2, 3, 4])

In [19]:
# Question 5
# accessing the third row and fourth column
arr[2,3] 

12

In [27]:
# Question 6
# accessing only the odd elements of the array
arr[:, [1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [28]:
import random

In [39]:
# Question 7
# creating random 3x3 array between 0,1
arr = np.random.rand(3,3)
arr

array([[0.35458802, 0.75821544, 0.49775006],
       [0.12870791, 0.80183533, 0.30562782],
       [0.25634196, 0.89090718, 0.20881239]])

In [40]:
# Question 8
# Answer) np.random.rand:
# This function generates random numbers from a uniform distribution over the interval [0, 1).
# It takes dimensions as input and returns an array of random numbers with the specified shape.

# np.random.randn:
# This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).
# It also takes dimensions as input and returns an array of random numbers with the specified shape.

In [49]:
# Question 9
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

# changing the dimension using reshape function 
arr.reshape(2,2,3)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
# Question 10 
# returning the transpose of an array, .T used for transpose
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [61]:
# Question 11
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
# i) index-wise multiplication 
a * b

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [62]:
# ii) matrix multiplication 
# to multiply these two matrix we have to reshape 1 matrix
sample = b.reshape(4,3)
a @ sample

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [65]:
# iii) addition of matrix
a + b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [66]:
# iv) subtraction 
a - b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [67]:
# v) divion 
a/b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
# Question 12
# In NumPy, you can use the byteswap() method to swap the byte order of an array. 
# This method swaps the byte order of the elements in the array, effectively changing the endianness.


In [69]:
# Question 13
# The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a square matrix.
# In other words, it calculates the inverse of a given matrix.

# The significance of np.linalg.inv lies in various mathematical and computational applications.

In [70]:
# Question 14

# The np.reshape function in NumPy is used to change the dimension of an array without changing its data.
# It allows you to rearrange the elements of an array into a new shape while maintaining the same total number of elements.

In [ ]:
# Question 15
# Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined in arithmetic operations.
# NumPy performs broadcasting when it encounters arrays with different shapes during arithmetic operations,
# effectively extending smaller arrays to match the shape of larger arrays, thus enabling element-wise operations.